// Generated catalogue of every music track in MBII's official pk3s (so
// every player has them), with a friendly name and a category for
// "!jukebox search". The first JUKEBOX_FEATURED entries are the featured
// list "!jukebox" shows; their numbers must not change. Rename freely.
// The last field is the track's length in seconds, measured from the pk3
// (every MPEG frame counted), for autoplay.

#pragma once

#define JUKEBOX_FEATURED 21

static const jukeboxTrack_t kJukeboxTracks[] = {
	{ "Cantina Band", "music/mp/Cantina", "Party", 368 },
	{ "Cantina Band (house mix)", "music/cantina2", "Party", 918 },
	{ "Nar Shaddaa Cantina", "music/ns/nsmb2_cantina", "Party", 928 },
	{ "Nightclub", "music/nightclub", "Party", 216 },
	{ "Club Mix", "music/desertbreak/club1", "Party", 90 },
	{ "Jabba's Sail Barge", "music/mp/SailBarge", "Star Wars", 303 },
	{ "Duel of the Fates", "music/mb2_dotf/dotf", "Duels", 313 },
	{ "Battle of the Heroes", "music/mustafarduel/mustafarduel", "Duels", 237 },
	{ "KotOR Mix", "Music/KotorMix", "KOTOR", 286 },
	{ "LEGO Star Wars", "Music/legosw", "Games & Films", 137 },
	{ "Benny Hill", "music/mp/BennyHill", "Party", 39 },
	{ "Hammer Time", "music/hammertime", "Party", 264 },
	{ "Crazy Train", "music/crazytrain/crazytrain", "Party", 297 },
	{ "Strings of Life", "music/tlp/strings-of-life2", "Party", 530 },
	{ "The Ultimate Showdown", "Music/ultimate_showdown", "Party", 118 },
	{ "Pokemon Town", "Music/pokemon/ptown", "Games & Films", 101 },
	{ "Teenage Mutant Ninja Turtles", "Music/tmnt", "Games & Films", 62 },
	{ "Halo", "Music/halo_for", "Games & Films", 129 },
	{ "Portal", "music/portal", "Games & Films", 177 },
	{ "Mortal Kombat", "Music/mk", "Games & Films", 202 },
	{ "Lord of the Rings", "Music/lotr_hd", "Games & Films", 353 },
	{ "Alderaan", "music/alderaan", "Star Wars", 247 },
	{ "Terminator Theme", "music/Arctic", "Games & Films", 117 },
	{ "Artus Detention", "music/artus_detention/impbasec_action", "Star Wars", 73 },
	{ "Asteroid Field", "music/asteroids", "Star Wars", 256 },
	{ "Auralnauts: Dark Side Mix", "music/assaultv2/auralnauts_darksideEP_mix", "Star Wars", 301 },
	{ "Auralnauts: Snoke", "music/auralnauts_snoke", "Star Wars", 271 },
	{ "Battle of Coruscant", "music/epiii_boc/battle", "Star Wars", 222 },
	{ "Battle of Coruscant (siege)", "music/epiii_boc/siege_boc", "Star Wars", 357 },
	{ "Bespin", "music/Bespin2/Bespin2song", "Star Wars", 915 },
	{ "Bespin (tourney)", "music/Bespin2/Bespin2tourney", "Star Wars", 912 },
	{ "Cloud City", "music/cc/cloudcity", "Star Wars", 328 },
	{ "Corellia", "music/music_corellia", "Star Wars", 303 },
	{ "Coruscant Chase", "music/mb2_coruscantchase", "Star Wars", 332 },
	{ "Coruscant Undercity", "music/coruscantuc", "Star Wars", 78 },
	{ "Death Star (CTF)", "music/mb2_ctf_deathstar", "Star Wars", 616 },
	{ "Echo Base", "music/mb2_echobase", "Star Wars", 323 },
	{ "Forest Battle", "music/forestbattle", "Star Wars", 246 },
	{ "General Grievous", "music/grievous", "Star Wars", 247 },
	{ "Good and Evil", "music/goodandevil", "Star Wars", 128 },
	{ "Jabba's Sail Barge (alternate)", "music/sailbargealternate", "Star Wars", 303 },
	{ "Jango's Escape", "Music/JangosEscape", "Star Wars", 229 },
	{ "Jawa Race", "music/jawarace", "Star Wars", 72 },
	{ "Jedha", "music/jedha", "Star Wars", 223 },
	{ "Jedi", "music/jedi", "Star Wars", 236 },
	{ "Jedi Academy Theme 1", "music/mp/10ree001", "Star Wars", 1 },
	{ "Jedi Academy Theme 2", "music/mp/10ree004", "Star Wars", 4 },
	{ "Jedi Enclave", "music/mb2_enclave", "Star Wars", 83 },
	{ "Jedi Enclave (explore)", "music/mb2_enclave_explore", "Star Wars", 78 },
	{ "Jedi Enclave (finale)", "music/mb2_enclave_final", "Star Wars", 120 },
	{ "Jedi Temple", "music/mb2_jeditemple", "Star Wars", 329 },
	{ "Kejim Base", "music/kejim_base/kejimbase_action", "Star Wars", 103 },
	{ "Kejim Outpost", "music/kejim_post/impbaseb_action", "Star Wars", 111 },
	{ "Korriban", "music/kor_lite/korrib_action1", "Star Wars", 15 },
	{ "Kyle's Game", "music/kylesgame", "Star Wars", 143 },
	{ "Massassi Temple", "music/MB2_CMP_Massassi", "Star Wars", 204 },
	{ "MBII Theme B17", "music/ThemeMusicB17", "Star Wars", 181 },
	{ "MBII Theme B18", "music/ThemeMusicB18", "Star Wars", 316 },
	{ "MBII Theme B19", "music/ThemeMusicB19", "Star Wars", 206 },
	{ "Movie Battles II Credits", "music/MBIICredits", "Star Wars", 139 },
	{ "Mustafar", "Music/mustafar", "Star Wars", 327 },
	{ "Mygeeto", "music/mygeeto1c", "Star Wars", 203 },
	{ "Onderon", "music/onderon", "Star Wars", 232 },
	{ "Palpatine's Office", "music/palpatines_office", "Star Wars", 98 },
	{ "Ravager", "music/rav/ravager", "Star Wars", 164 },
	{ "Republic Commando Hangar", "music/RC_HangarC", "Star Wars", 318 },
	{ "Republic Cruiser", "music/rc/mb2republiccruiser", "Star Wars", 314 },
	{ "Republic Cruiser Detention", "music/rc/mb2rcdetention", "Star Wars", 83 },
	{ "Scarif", "music/scarif", "Star Wars", 175 },
	{ "Smuggler's Base", "music/mb2_smuggler", "Star Wars", 326 },
	{ "Starkiller Base", "Music/starkiller_base", "Star Wars", 276 },
	{ "Tantive IV", "music/mb2_tantiveiv", "Star Wars", 403 },
	{ "The Citadel", "music/mb2_citadel", "Star Wars", 300 },
	{ "The Death Star", "music/The_Deathstar", "Star Wars", 327 },
	{ "The Emperor", "music/emperor/emperor", "Star Wars", 305 },
	{ "The Senate", "music/mb2_senate", "Star Wars", 291 },
	{ "Theed", "music/theed/theed", "Star Wars", 203 },
	{ "Tusken Camp", "music/mb2_tuskencamp", "Star Wars", 341 },
	{ "Valley of the Jedi", "Music/VOTJ", "Star Wars", 290 },
	{ "X-Wing", "music/xwing_music", "Star Wars", 320 },
	{ "Yavin Ruins", "music/yavinruins", "Star Wars", 182 },
	{ "Yavin Valley", "music/yavinValley/yavinValley", "Star Wars", 1020 },
	{ "Delta Prime", "music/deltaprime", "KOTOR", 325 },
	{ "KotOR II: Telos", "music/telos", "KOTOR", 80 },
	{ "KotOR: Hrakert Rift", "music/hrakert", "KOTOR", 88 },
	{ "KotOR: Leviathan Battle", "music/mleviathan/KotorBattle", "KOTOR", 210 },
	{ "KotOR: Manaan", "music/manaan", "KOTOR", 89 },
	{ "KotOR: Nar Shaddaa", "music/kotorns", "KOTOR", 272 },
	{ "KotOR: Selkath Ambush", "music/selkath_ambush", "KOTOR", 87 },
	{ "KotOR: Star Forge Battle", "music/starforge/KotorBattleMix", "KOTOR", 210 },
	{ "KotOR: Taris", "music/taris/Taris", "KOTOR", 142 },
	{ "KotOR: Taris (alternate)", "music/taris/Mace_Taris", "KOTOR", 325 },
	{ "Cloud City Duel", "music/duelcc/Duel_CC", "Duels", 405 },
	{ "Coruscant Duel", "Music/crt_duel", "Duels", 183 },
	{ "Coruscant Duel 2", "Music/crt_duel2", "Duels", 407 },
	{ "Dantooine Duel", "music/mb2_duel_dantooine", "Duels", 83 },
	{ "Duel (PRF)", "music/prf_duel", "Duels", 62 },
	{ "Duel (WBW)", "Music/mb2_duel_wbw", "Duels", 321 },
	{ "Duel of the Fates (classic)", "music/mb2_dotf/dotf_classic", "Duels", 245 },
	{ "Duel of the Fates (duel)", "music/mb2_dotf/duel_dotf", "Duels", 495 },
	{ "Dune Sea Duel", "music/mb2_duneseaduel", "Duels", 245 },
	{ "Malachor Duel", "Music/malachor_duel", "Duels", 304 },
	{ "Mustafar Duel", "Music/mustafarduel", "Duels", 325 },
	{ "Pistol Duel", "music/pistolduel", "Duels", 162 },
	{ "Starkiller Base Duel", "Music/skb_duel", "Duels", 194 },
	{ "Supremacy Duel", "Music/sup_duel", "Duels", 123 },
	{ "300", "Music/300", "Games & Films", 156 },
	{ "Alien 3 (part 1)", "Music/aliens31", "Games & Films", 103 },
	{ "Alien 3 (part 2)", "Music/aliens32", "Games & Films", 103 },
	{ "Alien 3 (part 3)", "Music/aliens33", "Games & Films", 97 },
	{ "Aliens", "Music/aliens2", "Games & Films", 134 },
	{ "Aliens (alternate)", "Music/alients2", "Games & Films", 519 },
	{ "Aliens (MGM)", "Music/mgmaliens", "Games & Films", 137 },
	{ "Braveheart", "music/braveheart/braveheart", "Games & Films", 279 },
	{ "Call of Duty 4", "Music/cod4", "Games & Films", 315 },
	{ "Castlevania", "music/castlevania/um_music", "Games & Films", 190 },
	{ "Counter-Strike: Dust 2", "Music/mb2_cmp_dust2/dust2", "Games & Films", 128 },
	{ "Crazy Race", "music/crazyrace", "Games & Films", 197 },
	{ "Crazy Race 2", "music/crazyrace2/crazyrace2", "Games & Films", 207 },
	{ "DC Universe", "Music/dc_universe", "Games & Films", 129 },
	{ "FIFA Champions League", "Music/fifa_cl", "Games & Films", 181 },
	{ "Final Fantasy VII: Church", "Music/midgar_v3/church", "Games & Films", 247 },
	{ "Final Fantasy VII: Shinra HQ", "Music/midgar_v3/shinrahq", "Games & Films", 228 },
	{ "Frozen Wheel", "music/bouncy/frozen_wheel", "Games & Films", 311 },
	{ "Giant Enemy Frog Who Eats Cats", "music/dreamtime/GiantEnemyFrogWhoEatsCats", "Games & Films", 267 },
	{ "Halo (alternate)", "Music/halobc", "Games & Films", 315 },
	{ "Jerusalem Horse Ride", "music/antioch/JerusalemHorseRide", "Games & Films", 220 },
	{ "Jurassic Park", "Music/jp", "Games & Films", 194 },
	{ "Lobby", "Music/Lobby", "Games & Films", 241 },
	{ "MediEvil", "music/medi-evil", "Games & Films", 300 },
	{ "Metal Gear Solid: Ocelot", "Music/Ocelot", "Games & Films", 258 },
	{ "Metal Gear Solid: VR", "Music/mgsvrdm", "Games & Films", 159 },
	{ "Monster Forest", "Music/monster_forest", "Games & Films", 122 },
	{ "Ninja", "Music/ninja", "Games & Films", 327 },
	{ "Omaha Beach", "Music/omaha", "Games & Films", 555 },
	{ "Pokemon Stadium", "Music/pkmnstad", "Games & Films", 108 },
	{ "Resident Evil: Mansion", "Music/re_mansion", "Games & Films", 200 },
	{ "Resident Evil: Mansion 2", "Music/re_mansion2", "Games & Films", 86 },
	{ "Resident Evil: Mansion 3", "Music/re_mansion3", "Games & Films", 198 },
	{ "Shogun Samurai", "Music/shogun_sam", "Games & Films", 162 },
	{ "Slender 1", "Music/slender_1", "Games & Films", 8 },
	{ "Slender 2", "Music/slender_2", "Games & Films", 8 },
	{ "Slender 3", "Music/slender_3", "Games & Films", 8 },
	{ "Slender 4", "Music/slender_4", "Games & Films", 8 },
	{ "Spider-Man 3", "Music/spiderman3", "Games & Films", 123 },
	{ "Star World", "music/dreamtime/StarWorld", "Games & Films", 112 },
	{ "Tennis: Buzz", "music/tennis2/buzz", "Games & Films", 1 },
	{ "Tennis: Score", "music/tennis2/score", "Games & Films", 1 },
	{ "Tennis: Thesis", "music/tennis2/thesis", "Games & Films", 203 },
	{ "Wipeout", "music/swoop/wipeout_tentative", "Games & Films", 327 },
	{ "Zelda: Shadow Temple", "music/swoop/zreo_shadow_temple", "Games & Films", 134 },
	{ "After Goal", "music/AfterGoal", "Maps", 332 },
	{ "AGear", "Music/AGear", "Maps", 172 },
	{ "Arena", "music/geoarena/arena", "Maps", 157 },
	{ "Ascension2", "music/Ascension2", "Maps", 244 },
	{ "Base Scream", "music/cislabs/base_scream", "Maps", 3 },
	{ "Bbrawl", "Music/bbrawl", "Maps", 532 },
	{ "Birdmino", "music/Birdmino", "Maps", 258 },
	{ "Calodan", "music/calodan/calodan", "Maps", 960 },
	{ "Canyonsoundset", "music/canyon/canyonsoundset", "Maps", 37 },
	{ "Cargoheist", "music/cargoheist", "Maps", 433 },
	{ "Comm Tower", "music/mb2_comm_tower/CommTower", "Maps", 306 },
	{ "Cot1", "music/cot1", "Maps", 257 },
	{ "Ctf Rift Song", "music/ctf_rift/ctf_rift_song", "Maps", 930 },
	{ "Doomgiver1", "music/cmp_doomgiver/doomgiver1", "Maps", 93 },
	{ "Elcargo", "music/mb2_assault/elcargo", "Maps", 252 },
	{ "Elcargo Old", "music/mb2_assault/elcargo_old", "Maps", 264 },
	{ "Eravana", "Music/eravana", "Maps", 246 },
	{ "FDepot", "music/FDepot", "Maps", 97 },
	{ "Fortune", "Music/fortune", "Maps", 150 },
	{ "Glass Song", "music/glass_song", "Maps", 173 },
	{ "Hotfo2a", "music/hotfo2a", "Maps", 308 },
	{ "Jf Sniper", "music/jf_sniper", "Maps", 393 },
	{ "Jku Assault", "Music/jku_assault", "Maps", 199 },
	{ "Labmusic", "music/Labmusic", "Maps", 93 },
	{ "Mus Bat Gang", "music/cmp_raxus/mus_bat_gang", "Maps", 81 },
	{ "Nightmare", "music/music/mb2_nightmare", "Maps", 211 },
	{ "Oceantemple", "music/oceantemple", "Maps", 900 },
	{ "Olympus", "music/olympus/olympus", "Maps", 930 },
	{ "PDC", "music/mp/PDC", "Maps", 148 },
	{ "Peace", "music/Peace", "Maps", 134 },
	{ "Pretzalprime", "music/hetzal/pretzalprime", "Maps", 252 },
	{ "Raidmix", "music/raidmix", "Maps", 231 },
	{ "Reactor", "music/mb2_cmp_reactor", "Maps", 309 },
	{ "Rescue", "music/mb2_cmp_rescue", "Maps", 343 },
	{ "Sabh", "music/mb2_sabh", "Maps", 300 },
	{ "Sandbarge", "music/sandy", "Star Wars", 303 },
	{ "Smile", "music/smile", "Maps", 8 },
	{ "Syndicate", "music/syndicate", "Maps", 150 },
	{ "Tfed", "Music/tfed", "Maps", 210 },
	{ "Thermae", "music/thermae/thermae", "Maps", 929 },
	{ "Thesis", "music/breakfloor/thesis", "Maps", 203 },
	{ "Throwthemin", "music/throwthemin", "Maps", 157 },
	{ "Track13", "music/cislabs/track13", "Maps", 119 },
	{ "Transport Theme", "music/mb2_cmp_transport/transport_theme", "Maps", 185 },
	{ "Tuxedomoon", "music/tuxedomoon", "Maps", 330 },
	{ "Um Dojo V2", "music/um_dojo_v2", "Maps", 393 },
	{ "Underground", "music/underground/underground", "Maps", 931 },
	{ "Vodean", "Music/vodean", "Maps", 280 },
};
