// Generated catalogue of every music track in MBII's official pk3s (so
// every player has them), with a friendly name and a category for
// "!jukebox search". The first JUKEBOX_FEATURED entries are the featured
// list "!jukebox" shows; their numbers must not change. Rename freely.

#pragma once

#define JUKEBOX_FEATURED 21

static const jukeboxTrack_t kJukeboxTracks[] = {
	{ "Cantina Band", "music/mp/Cantina", "Party" },
	{ "Cantina Band (house mix)", "music/cantina2", "Party" },
	{ "Nar Shaddaa Cantina", "music/ns/nsmb2_cantina", "Party" },
	{ "Nightclub", "music/nightclub", "Party" },
	{ "Club Mix", "music/desertbreak/club1", "Party" },
	{ "Jabba's Sail Barge", "music/mp/SailBarge", "Star Wars" },
	{ "Duel of the Fates", "music/mb2_dotf/dotf", "Duels" },
	{ "Battle of the Heroes", "music/mustafarduel/mustafarduel", "Duels" },
	{ "KotOR Mix", "Music/KotorMix", "KOTOR" },
	{ "LEGO Star Wars", "Music/legosw", "Games & Films" },
	{ "Benny Hill", "music/mp/BennyHill", "Party" },
	{ "Hammer Time", "music/hammertime", "Party" },
	{ "Crazy Train", "music/crazytrain/crazytrain", "Party" },
	{ "Strings of Life", "music/tlp/strings-of-life2", "Party" },
	{ "The Ultimate Showdown", "Music/ultimate_showdown", "Party" },
	{ "Pokemon Town", "Music/pokemon/ptown", "Games & Films" },
	{ "Teenage Mutant Ninja Turtles", "Music/tmnt", "Games & Films" },
	{ "Halo", "Music/halo_for", "Games & Films" },
	{ "Portal", "music/portal", "Games & Films" },
	{ "Mortal Kombat", "Music/mk", "Games & Films" },
	{ "Lord of the Rings", "Music/lotr_hd", "Games & Films" },
	{ "Alderaan", "music/alderaan", "Star Wars" },
	{ "Arctic", "music/Arctic", "Star Wars" },
	{ "Artus Detention", "music/artus_detention/impbasec_action", "Star Wars" },
	{ "Asteroid Field", "music/asteroids", "Star Wars" },
	{ "Auralnauts: Dark Side Mix", "music/assaultv2/auralnauts_darksideEP_mix", "Star Wars" },
	{ "Auralnauts: Snoke", "music/auralnauts_snoke", "Star Wars" },
	{ "Battle of Coruscant", "music/epiii_boc/battle", "Star Wars" },
	{ "Battle of Coruscant (siege)", "music/epiii_boc/siege_boc", "Star Wars" },
	{ "Bespin", "music/Bespin2/Bespin2song", "Star Wars" },
	{ "Bespin (tourney)", "music/Bespin2/Bespin2tourney", "Star Wars" },
	{ "Cloud City", "music/cc/cloudcity", "Star Wars" },
	{ "Corellia", "music/music_corellia", "Star Wars" },
	{ "Coruscant Chase", "music/mb2_coruscantchase", "Star Wars" },
	{ "Coruscant Undercity", "music/coruscantuc", "Star Wars" },
	{ "Death Star (CTF)", "music/mb2_ctf_deathstar", "Star Wars" },
	{ "Echo Base", "music/mb2_echobase", "Star Wars" },
	{ "Forest Battle", "music/forestbattle", "Star Wars" },
	{ "General Grievous", "music/grievous", "Star Wars" },
	{ "Good and Evil", "music/goodandevil", "Star Wars" },
	{ "Jabba's Sail Barge (alternate)", "music/sailbargealternate", "Star Wars" },
	{ "Jango's Escape", "Music/JangosEscape", "Star Wars" },
	{ "Jawa Race", "music/jawarace", "Star Wars" },
	{ "Jedha", "music/jedha", "Star Wars" },
	{ "Jedi", "music/jedi", "Star Wars" },
	{ "Jedi Academy Theme 1", "music/mp/10ree001", "Star Wars" },
	{ "Jedi Academy Theme 2", "music/mp/10ree004", "Star Wars" },
	{ "Jedi Enclave", "music/mb2_enclave", "Star Wars" },
	{ "Jedi Enclave (explore)", "music/mb2_enclave_explore", "Star Wars" },
	{ "Jedi Enclave (finale)", "music/mb2_enclave_final", "Star Wars" },
	{ "Jedi Temple", "music/mb2_jeditemple", "Star Wars" },
	{ "Kejim Base", "music/kejim_base/kejimbase_action", "Star Wars" },
	{ "Kejim Outpost", "music/kejim_post/impbaseb_action", "Star Wars" },
	{ "Korriban", "music/kor_lite/korrib_action1", "Star Wars" },
	{ "Kyle's Game", "music/kylesgame", "Star Wars" },
	{ "Massassi Temple", "music/MB2_CMP_Massassi", "Star Wars" },
	{ "MBII Theme B17", "music/ThemeMusicB17", "Star Wars" },
	{ "MBII Theme B18", "music/ThemeMusicB18", "Star Wars" },
	{ "MBII Theme B19", "music/ThemeMusicB19", "Star Wars" },
	{ "Movie Battles II Credits", "music/MBIICredits", "Star Wars" },
	{ "Mustafar", "Music/mustafar", "Star Wars" },
	{ "Mygeeto", "music/mygeeto1c", "Star Wars" },
	{ "Onderon", "music/onderon", "Star Wars" },
	{ "Palpatine's Office", "music/palpatines_office", "Star Wars" },
	{ "Ravager", "music/rav/ravager", "Star Wars" },
	{ "Republic Commando Hangar", "music/RC_HangarC", "Star Wars" },
	{ "Republic Cruiser", "music/rc/mb2republiccruiser", "Star Wars" },
	{ "Republic Cruiser Detention", "music/rc/mb2rcdetention", "Star Wars" },
	{ "Scarif", "music/scarif", "Star Wars" },
	{ "Smuggler's Base", "music/mb2_smuggler", "Star Wars" },
	{ "Starkiller Base", "Music/starkiller_base", "Star Wars" },
	{ "Tantive IV", "music/mb2_tantiveiv", "Star Wars" },
	{ "The Citadel", "music/mb2_citadel", "Star Wars" },
	{ "The Death Star", "music/The_Deathstar", "Star Wars" },
	{ "The Emperor", "music/emperor/emperor", "Star Wars" },
	{ "The Senate", "music/mb2_senate", "Star Wars" },
	{ "Theed", "music/theed/theed", "Star Wars" },
	{ "Tusken Camp", "music/mb2_tuskencamp", "Star Wars" },
	{ "Valley of the Jedi", "Music/VOTJ", "Star Wars" },
	{ "X-Wing", "music/xwing_music", "Star Wars" },
	{ "Yavin Ruins", "music/yavinruins", "Star Wars" },
	{ "Yavin Valley", "music/yavinValley/yavinValley", "Star Wars" },
	{ "Delta Prime", "music/deltaprime", "KOTOR" },
	{ "KotOR II: Telos", "music/telos", "KOTOR" },
	{ "KotOR: Hrakert Rift", "music/hrakert", "KOTOR" },
	{ "KotOR: Leviathan Battle", "music/mleviathan/KotorBattle", "KOTOR" },
	{ "KotOR: Manaan", "music/manaan", "KOTOR" },
	{ "KotOR: Nar Shaddaa", "music/kotorns", "KOTOR" },
	{ "KotOR: Selkath Ambush", "music/selkath_ambush", "KOTOR" },
	{ "KotOR: Star Forge Battle", "music/starforge/KotorBattleMix", "KOTOR" },
	{ "KotOR: Taris", "music/taris/Taris", "KOTOR" },
	{ "KotOR: Taris (alternate)", "music/taris/Mace_Taris", "KOTOR" },
	{ "Cloud City Duel", "music/duelcc/Duel_CC", "Duels" },
	{ "Coruscant Duel", "Music/crt_duel", "Duels" },
	{ "Coruscant Duel 2", "Music/crt_duel2", "Duels" },
	{ "Dantooine Duel", "music/mb2_duel_dantooine", "Duels" },
	{ "Duel (PRF)", "music/prf_duel", "Duels" },
	{ "Duel (WBW)", "Music/mb2_duel_wbw", "Duels" },
	{ "Duel of the Fates (classic)", "music/mb2_dotf/dotf_classic", "Duels" },
	{ "Duel of the Fates (duel)", "music/mb2_dotf/duel_dotf", "Duels" },
	{ "Dune Sea Duel", "music/mb2_duneseaduel", "Duels" },
	{ "Malachor Duel", "Music/malachor_duel", "Duels" },
	{ "Mustafar Duel", "Music/mustafarduel", "Duels" },
	{ "Pistol Duel", "music/pistolduel", "Duels" },
	{ "Starkiller Base Duel", "Music/skb_duel", "Duels" },
	{ "Supremacy Duel", "Music/sup_duel", "Duels" },
	{ "300", "Music/300", "Games & Films" },
	{ "Alien 3 (part 1)", "Music/aliens31", "Games & Films" },
	{ "Alien 3 (part 2)", "Music/aliens32", "Games & Films" },
	{ "Alien 3 (part 3)", "Music/aliens33", "Games & Films" },
	{ "Aliens", "Music/aliens2", "Games & Films" },
	{ "Aliens (alternate)", "Music/alients2", "Games & Films" },
	{ "Aliens (MGM)", "Music/mgmaliens", "Games & Films" },
	{ "Braveheart", "music/braveheart/braveheart", "Games & Films" },
	{ "Call of Duty 4", "Music/cod4", "Games & Films" },
	{ "Castlevania", "music/castlevania/um_music", "Games & Films" },
	{ "Counter-Strike: Dust 2", "Music/mb2_cmp_dust2/dust2", "Games & Films" },
	{ "Crazy Race", "music/crazyrace", "Games & Films" },
	{ "Crazy Race 2", "music/crazyrace2/crazyrace2", "Games & Films" },
	{ "DC Universe", "Music/dc_universe", "Games & Films" },
	{ "FIFA Champions League", "Music/fifa_cl", "Games & Films" },
	{ "Final Fantasy VII: Church", "Music/midgar_v3/church", "Games & Films" },
	{ "Final Fantasy VII: Shinra HQ", "Music/midgar_v3/shinrahq", "Games & Films" },
	{ "Frozen Wheel", "music/bouncy/frozen_wheel", "Games & Films" },
	{ "Giant Enemy Frog Who Eats Cats", "music/dreamtime/GiantEnemyFrogWhoEatsCats", "Games & Films" },
	{ "Halo (alternate)", "Music/halobc", "Games & Films" },
	{ "Jerusalem Horse Ride", "music/antioch/JerusalemHorseRide", "Games & Films" },
	{ "Jurassic Park", "Music/jp", "Games & Films" },
	{ "Lobby", "Music/Lobby", "Games & Films" },
	{ "MediEvil", "music/medi-evil", "Games & Films" },
	{ "Metal Gear Solid: Ocelot", "Music/Ocelot", "Games & Films" },
	{ "Metal Gear Solid: VR", "Music/mgsvrdm", "Games & Films" },
	{ "Monster Forest", "Music/monster_forest", "Games & Films" },
	{ "Ninja", "Music/ninja", "Games & Films" },
	{ "Omaha Beach", "Music/omaha", "Games & Films" },
	{ "Pokemon Stadium", "Music/pkmnstad", "Games & Films" },
	{ "Resident Evil: Mansion", "Music/re_mansion", "Games & Films" },
	{ "Resident Evil: Mansion 2", "Music/re_mansion2", "Games & Films" },
	{ "Resident Evil: Mansion 3", "Music/re_mansion3", "Games & Films" },
	{ "Shogun Samurai", "Music/shogun_sam", "Games & Films" },
	{ "Slender 1", "Music/slender_1", "Games & Films" },
	{ "Slender 2", "Music/slender_2", "Games & Films" },
	{ "Slender 3", "Music/slender_3", "Games & Films" },
	{ "Slender 4", "Music/slender_4", "Games & Films" },
	{ "Spider-Man 3", "Music/spiderman3", "Games & Films" },
	{ "Star World", "music/dreamtime/StarWorld", "Games & Films" },
	{ "Tennis: Buzz", "music/tennis2/buzz", "Games & Films" },
	{ "Tennis: Score", "music/tennis2/score", "Games & Films" },
	{ "Tennis: Thesis", "music/tennis2/thesis", "Games & Films" },
	{ "Wipeout", "music/swoop/wipeout_tentative", "Games & Films" },
	{ "Zelda: Shadow Temple", "music/swoop/zreo_shadow_temple", "Games & Films" },
	{ "After Goal", "music/AfterGoal", "Maps" },
	{ "AGear", "Music/AGear", "Maps" },
	{ "Arena", "music/geoarena/arena", "Maps" },
	{ "Ascension2", "music/Ascension2", "Maps" },
	{ "Base Scream", "music/cislabs/base_scream", "Maps" },
	{ "Bbrawl", "Music/bbrawl", "Maps" },
	{ "Birdmino", "music/Birdmino", "Maps" },
	{ "Calodan", "music/calodan/calodan", "Maps" },
	{ "Canyonsoundset", "music/canyon/canyonsoundset", "Maps" },
	{ "Cargoheist", "music/cargoheist", "Maps" },
	{ "Comm Tower", "music/mb2_comm_tower/CommTower", "Maps" },
	{ "Cot1", "music/cot1", "Maps" },
	{ "Ctf Rift Song", "music/ctf_rift/ctf_rift_song", "Maps" },
	{ "Doomgiver1", "music/cmp_doomgiver/doomgiver1", "Maps" },
	{ "Elcargo", "music/mb2_assault/elcargo", "Maps" },
	{ "Elcargo Old", "music/mb2_assault/elcargo_old", "Maps" },
	{ "Eravana", "Music/eravana", "Maps" },
	{ "FDepot", "music/FDepot", "Maps" },
	{ "Fortune", "Music/fortune", "Maps" },
	{ "Glass Song", "music/glass_song", "Maps" },
	{ "Hotfo2a", "music/hotfo2a", "Maps" },
	{ "Jf Sniper", "music/jf_sniper", "Maps" },
	{ "Jku Assault", "Music/jku_assault", "Maps" },
	{ "Labmusic", "music/Labmusic", "Maps" },
	{ "Mus Bat Gang", "music/cmp_raxus/mus_bat_gang", "Maps" },
	{ "Nightmare", "music/music/mb2_nightmare", "Maps" },
	{ "Oceantemple", "music/oceantemple", "Maps" },
	{ "Olympus", "music/olympus/olympus", "Maps" },
	{ "PDC", "music/mp/PDC", "Maps" },
	{ "Peace", "music/Peace", "Maps" },
	{ "Pretzalprime", "music/hetzal/pretzalprime", "Maps" },
	{ "Raidmix", "music/raidmix", "Maps" },
	{ "Reactor", "music/mb2_cmp_reactor", "Maps" },
	{ "Rescue", "music/mb2_cmp_rescue", "Maps" },
	{ "Sabh", "music/mb2_sabh", "Maps" },
	{ "Sandy", "music/sandy", "Maps" },
	{ "Smile", "music/smile", "Maps" },
	{ "Syndicate", "music/syndicate", "Maps" },
	{ "Tfed", "Music/tfed", "Maps" },
	{ "Thermae", "music/thermae/thermae", "Maps" },
	{ "Thesis", "music/breakfloor/thesis", "Maps" },
	{ "Throwthemin", "music/throwthemin", "Maps" },
	{ "Track13", "music/cislabs/track13", "Maps" },
	{ "Transport Theme", "music/mb2_cmp_transport/transport_theme", "Maps" },
	{ "Tuxedomoon", "music/tuxedomoon", "Maps" },
	{ "Um Dojo V2", "music/um_dojo_v2", "Maps" },
	{ "Underground", "music/underground/underground", "Maps" },
	{ "Vodean", "Music/vodean", "Maps" },
};
